### ISSUE TITLE
Integrate GitHub Gatsby API

### ISSUE THREAD

**Issue by Ry-DS** [Korusuke/MLH-Fellow-Map#46]
A util class to get details for a fellow from the github api.

Details such as:
- Name
- Profile picture url
- Default GitHub Bio
- Recent projects worked on during the fellowship
- Pod image url and name
- **Add more here by editing**

Use: https://github.com/ldd/gatsby-source-github-api

**Comment by Korusuke** [comment]
While researching into GitHub API (both graphql and Rest), the major downside is MLH org is semi-private and not all fellows have their profile open.

If we want to get all the data of MLH org then we will have to use our Github token, which will not only be a pain to set up with CI/CD but also won't allow easy testing for other fellows on their local machines.

Also looking into the [fellowbook](https://github.com/MLH-Fellowship/0.2.1-fellowbook) I found that they have explicitly mentioned the privacy point that we discussed earlier.

![image](https://user-images.githubusercontent.com/15181757/87432370-87944a00-c605-11ea-8d1e-df164cf6d165.png)


Keeping all this in mind I think we should keep `Fellow-Map` opt-in only and allow fellows what info would they like to keep open to the world. This can be either done by fellow manually filling out a `json` or `mdx` file with below info:

```
{
    "avatar_url": "https://avatars0.githubusercontent.com/u/15181757?u=fb42a25ff7353060b85c0f3c2df15eed6632ca93&v=4",
    "bio": "Scrape Everything!",
    "email": "karan.sheth@somaiya.edu",
    "followers": 80,
    "following": 59,
    "location": null,
    "username": "korusuke",
    "username_original": "Korusuke",
    "name": "Karan Sheth",
    "twitter_username": "kiteretsu_",
    "github_url": "https://github.com/Korusuke",
    "website_url": "kiteretsu.tech",
    "company": null,
    "pod": "Smart Sea Cucumbers",
    "pod_id": "0.1.1"
  }
```

or we can have some script that our CI/CD or Github Bot runs and commits this info intto the repo once any fellow has made their first commit (this would be considered as permission to display their information)

**Side Note**: The above json is all the information that the `fellowbook` used.

**Comment by Ry-DS** [comment]
> ... snipped
> **Side Note**: The above json is all the information that the `fellowbook` used. 

Ah I see, those are some good points. 

I think CD won't be too hard since we can set environment variables within the github action with a secret and since the Gatsby config is a JS file, we can grab it directly with `process.env`. For local testing, we could explicitly say in the Readme you need to provide your own github token as an environment variable using `.env` or `cross-env`.

For opt-in, we can try simplify it by just telling users to add themselves to a list of usernames if we can pull off this GitHub API stuff. Or we could try see if we can contact Will to see if keeping it default opt in is ok, especially for the hackathon - it'll look quite impressive!
