### ISSUE TITLE
Compress Images

### ISSUE THREAD

**Issue by Korusuke** [Korusuke/MLH-Fellow-Map#8]
Add a Github action workflow so Images are compressed so as to reduce the load time and network usage.

**Comment by Korusuke** [comment]
Another option would be to get Gatsby to compress those images and make leaflet work with gatsby images.

**Comment by Ry-DS** [comment]
After PR #13, what's still needed to fix this issue?

**Comment by Ry-DS** [comment]
Use: https://www.gatsbyjs.org/packages/gatsby-image/
Support for users to provide their own image or use github's profile picture
